name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up sdl2
      run: |
        sudo apt -y install libsdl2{,-image,-mixer,-ttf,-gfx}-dev
        sudo apt -y install build-essential libgtk-3-dev

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Install
      run: make install && make tools

    - name: Test
      run: make test

    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Linter
      run: make lint

    - name: Build
      run: make build1

    - name: Build2
      run: make build2

    - name: release
      run: cp config.json bin/config.json && cp -r resources bin/resources && zip -qq -r golauncher-minecraft bin