name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Install
      run: make install && make tools

    - name: Linter
      run: make lint

    - name: pull docker
      run: docker pull ymohlcl/gosdl2:0.0.3

    - name: test
      run: docker run -t -v $PWD:/go/src/app -w/go/src/app ymohlcl/gosdl2:0.0.3 make test

    - name: coverage
      run: bash <(curl -s https://codecov.io/bash) -f `make covefile`

    - name: go_sdl2-actionbuilder
      id: go_sdl2-actionbuilder
      uses: ymohl-cl/go_sdl2_actionbuilder@v0.2.1
      with:
        gosdl2-version: '0.0.3'
        docker-context: .

      # tarball the result
    - name: pre-release
      run: |
        sudo cp config.json /github/workspace/bin/config.json \
          && sudo cp -r resources /github/workspace/bin/resources \
          && sudo zip -r /github/workspace/release.zip /github/workspace/bin

    - name: release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: $${{ secrets.GITHUB_TOKEN }}
      with:
        args: /github/workspace/release.zip
